version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: FileIntake/Dockerfile
        container_name: fileintake-web
        depends_on:
            - sql
        ports:
            - "8080:8080"
        environment:
            - ASPNETCORE_ENVIRONEMNT=Development
            - ConnectionStrings_DefaultConnection=Server=sql;Database=FileIntakeDB;User=sa;Password=password123;TrustServerCertificate=True;

    sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: fileintake-sql
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "password123"
        ports:
            - "1433:1433"
        volumes:
            - sql_data:/var/opt/mssql

volumes:
    sql_data:
